---
- name: Update APT cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade all base packages
  apt: upgrade=dist

- name: Clean out old packages if any
  command: apt-get -y autoremove

- name: Install Ubuntu packages
  apt: name={{ item }} state=present
  with_items:
      # For adding PPA's more easily
    - software-properties-common
      # Some npm (and other tools) install's can need this at times
    - build-essential
      # Some pip's can use this at times
    - python-dev
    - python-pip
      # Some gems can use this at times
    - ruby-dev
    - wget
    - curl
    - unzip
    - imagemagick
    - graphviz
      # Convert line endings
    - dos2unix
    - re2c
    - supervisor
    - whois
      # Install mailutils postfix for sending local emails
    - mailutils
    - postfix

- name: Listen only on the local interface
  lineinfile: dest=/etc/postfix/main.cf regexp='^inet_interfaces' line='inet_interfaces = 127.0.0.1'
  notify: restart postfix
  sudo: yes

# # Automatically install security upgrade
# - name: Install unattended-upgrades
#   apt: name={{ item }} state=present
#   with_items:
#     - unattended-upgrades

# Not generally needed by us, but here for reference.
# - name: Create locale
#   locale_gen: name=en_US.UTF-8 state=present
#
# - name: Set locale
#   lineinfile: line='LC_ALL=en_US.UTF-8' dest=/etc/default/locale

# Useful if your application needs to check the environment it's running on
- name: Export APPLICATION_ENV in .profile
  sudo_user: vagrant
  lineinfile:
    dest: "~/.profile"
    line: "export APPLICATION_ENV=local"
