---
- name: Update APT cache
  apt: update_cache=yes cache_valid_time=3600
  tags:
    - common

- name: Upgrade all base packages
  apt: upgrade=dist
  tags:
    - common

- name: Clean out old packages if any
  command: apt-get -y autoremove
  tags:
    - common

# Some npm (and other tools) install's can need this at times
# No harm in just installing it
- name: Install build-essential
  apt: name={{ item }} state=present
  with_items:
    - build-essential
  tags:
    - common

- name: Install wget
  apt: name={{ item }} state=present
  with_items:
    - wget
  tags:
    - common

- name: Install curl
  apt: name={{ item }} state=present
  with_items:
    - curl
  tags:
    - common

- name: Install unzip
  sudo: yes
  apt: name={{ item }} state=present
  with_items:
    - unzip
  tags:
    - common

# Useful if your application needs to check the environment it's running on
- name: Export APPLICATION_ENV in .profile
  sudo: yes
  sudo_user: vagrant
  lineinfile: >
    dest="~/.profile"
    line="export APPLICATION_ENV=local"
  tags:
    - common
