---
- name: Update APT cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade all base packages
  apt: upgrade=dist

- name: Clean out old packages if any
  command: apt-get -y autoremove

# Some npm (and other tools) install's can need this at times
- name: Install build-essential
  apt: name={{ item }} state=present
  with_items:
    - build-essential

# Some pip's can use this at times
- name: Install python-dev
  apt: name={{ item }} state=present
  with_items:
    - python-dev

- name: Install python pip
  apt: name={{ item }} state=present
  with_items:
    - python-pip

# Some gems can use this at times
- name: Install ruby-dev
  apt: name={{ item }} state=present
  with_items:
    - ruby-dev

- name: Install wget
  apt: name={{ item }} state=present
  with_items:
    - wget

- name: Install curl
  apt: name={{ item }} state=present
  with_items:
    - curl

- name: Install unzip
  apt: name={{ item }} state=present
  with_items:
    - unzip

- name: Install imagemagick
  apt: name={{ item }} state=present
  with_items:
    - imagemagick

- name: Install graphviz
  apt: name={{ item }} state=present
  with_items:
    - graphviz

# For adding PPA's more easily
- name: Install software-properties-common
  apt: name={{ item }} state=present
  with_items:
    - software-properties-common

# Useful if your application needs to check the environment it's running on
- name: Export APPLICATION_ENV in .profile
  sudo_user: vagrant
  lineinfile: >
    dest="~/.profile"
    line="export APPLICATION_ENV=local"
