---
- name: Update APT cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade all base packages
  apt: upgrade=dist

- name: Clean out old packages if any
  command: apt-get -y autoremove

# Some npm (and other tools) install's can need this at times
# No harm in just installing it
- name: Install build-essential
  apt: name={{ item }} state=present
  with_items:
    - build-essential

- name: Install wget
  apt: name={{ item }} state=present
  with_items:
    - wget

- name: Install curl
  apt: name={{ item }} state=present
  with_items:
    - curl

- name: Install unzip
  sudo: yes
  apt: name={{ item }} state=present
  with_items:
    - unzip

# Useful if your application needs to check the environment it's running on
- name: Export APPLICATION_ENV in .profile
  sudo: yes
  sudo_user: vagrant
  lineinfile: >
    dest="~/.profile"
    line="export APPLICATION_ENV=local"
