---
allow_duplicates: no
dependencies:
  - role: database-config
    database_name: "{{ devstack_db_name }}"
    database_user: "{{ devstack_db_user }}"
    database_password: "{{ devstack_db_password }}"
    database_dump: "{{ devstack_db_dump }}"
