---
allow_duplicates: no
dependencies:
#   - { role: composer }
#   - { role: php }
#   - { role: apache }
#   - { role: mysql }
#   - { role: nodejs }
#   - { role: git }
#   - { role: common }
  - role: apache-config
    apache_name: "wordpress"
    apache_hostname: "{{ wordpress_hostname }}"
    apache_docroot: "{{ wordpress_docroot }}"
    apache_port: "{{ wordpress_port }}"
    apache_ssl_port: "{{ wordpress_ssl_port }}"
