---
allow_duplicates: no
dependencies:
#   - { role: composer }
#   - { role: php }
#   - { role: apache }
  - { role: apache-config, apache_docroot: "{{ wordpress_docroot }}" }
#   - { role: mysql }
#   - { role: nodejs }
#   - { role: git }
#   - { role: common }
