---
- name: Copy Acquia Cloud API
  copy:
    src: "{{ acquia_insight_capi }}/.acquia"
    dest: /home/vagrant

- name: Copy drush aliases
  copy:
    src: "{{ acquia_insight_capi }}/.drush/"
    dest: /home/vagrant/.drush

- name: Update drush commands
  command: drush cc drush

# - name: Update Drush aliases for all accessible Acquia Cloud sites
#   command: drush acquia-update
