---
- name: Install hosting services tools
  homebrew: name={{ item }} state=present update_homebrew=no
  with_items: hosting_services_brew

- name:  Install host hosting services node modules
  npm: name={{ item }} global=yes state=present
  with_items: hosting_services_npm

