---
## The bootstrap script makes sure that Homebrew is installed. Check the version.
- name: Get version information for Homebrew
  command: brew --version
  register: brew_version_raw
  changed_when: false

- name: Save the Homebrew version
  set_fact: brew_version="{{ brew_version_raw.stdout | regex_replace('^Homebrew ([0-9.]+).*$', '\\1') }}"

- name: Ensure that Homebrew is recent enough
  homebrew:
    update_homebrew: yes
  when: brew_version | version_compare(homebrew_min_version, '<')

- name: Tap the repo for Homebrew Cask
  homebrew_tap:
    name: caskroom/cask
    state: present

- name: List the installed casks
  command: brew cask list -1
  register: brew_cask_list_raw
  changed_when: false

- name: Parse the list of installed casks
  set_fact: brew_cask_list="{{ brew_cask_list_raw.stdout_lines }}"

- name: Install node.js and npm
  homebrew:
    name: node
    state: present
    install_options: with-npm
    update_homebrew: no

- name: Install bundler (for gem)
  gem:
    name: bundler
    state: present
