---
- name: Download Drupal console installer
  get_url: url=http://drupalconsole.com/installer dest=/tmp

- name: Run console installer
  shell: "php /tmp/installer"
  args:
    chdir: "/tmp"

- name: Enable console globally
  shell: "mv /tmp/console.phar /usr/local/bin/drupal"
  ignore_errors: yes
