---
- name: Configure Project VirtualHost
  template: src=../templates/vhost.conf.j2 dest=/etc/apache2/sites-available/{{ project_name }}.conf

- name: Configure Project HTTPS VirtualHost
  template: src=../templates/vhost-ssl.conf.j2 dest=/etc/apache2/sites-available/{{ project_name }}-ssl.conf

- name: Enable Project VirtualHost
  command: a2ensite {{ project_name }}

- name: Enable Project HTTPS VirtualHost
  command: a2ensite {{ project_name }}-ssl
