# Reference: https://laravel.com/docs/5.2
---
- name: Install laravel installer with composer
  become: no
  composer:
    command: "require"
    arguments: "laravel/installer{{ laravel_installer_version }}"
    working_dir: "{{ composer_home }}"

- name: Ensure that the document root exists.
  file: path="{{ laravel_base }}" state="directory"

- name: Create a Laravel project.
  become: no
  shell: laravel new {{ laravel_folder }}
  args:
    chdir: "{{ laravel_base }}"
    creates: "{{ laravel_base }}/{{ laravel_folder }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ composer_home }}/vendor/bin"

- name: Ensure that the web server can write to directories.
  file:
    path: "{{ laravel_base }}/{{ laravel_folder }}/{{ item }}"
    state: directory
    group: www-data
    mode: g+w
    recurse: yes
  with_items:
    - storage
    - bootstrap/cache

- name: Setting Laravel environment
  template:
    src=env.j2
    dest={{ laravel_base }}/{{ laravel_folder }}/.env
    force=yes

- name: Setting Laravel routes
  template:
    src=routes.php.j2
    dest={{ laravel_base }}/{{ laravel_folder }}/app/Http/routes.php
    owner=vagrant
    group=vagrant
    mode=0644
    force=yes

- name: Setting Laravel controller
  template:
    src=WelcomeController.php.j2
    dest={{ laravel_base }}/{{ laravel_folder }}/app/Http/Controllers/WelcomeController.php
    owner=vagrant
    group=vagrant
    mode=0644

- name: Setting Laravel
  copy:
    src=arrived.blade.php
    dest={{ laravel_base }}/{{ laravel_folder }}/resources/views/arrived.blade.php
    owner=vagrant
    group=vagrant
    mode=0644
