# Reference: https://laravel.com/docs/5.2
---
# TODO: there must be a better way to do this to make sure composer vars are
# used globally (not per task)?
- name: Source the system ENV (make sure ENV VARS load everywhere)
  shell: . /etc/environment

- name: Install laravel installer with composer
  become: yes
  become_user: vagrant
  command: composer global require "laravel/installer{{ laravel_installer_version }}"
  # command: composer global require --prefer-source "laravel/installer{{ laravel_installer_version }}"

- name: Ensure that the document root exists.
  file: path="{{ laravel_base }}" state="directory"

- name: Create a Laravel project.
  become: yes
  become_user: vagrant
  shell: laravel new {{ laravel_folder }}
  args:
    chdir: "{{ laravel_base }}"
    creates: "{{ laravel_base }}/{{ laravel_folder }}"

- name: Ensure that the web server can write to directories.
  file:
    path: "{{ laravel_base }}/{{ laravel_folder }}/{{ item }}"
    state: directory
    group: www-data
    mode: g+w
    recurse: yes
  with_items:
    - storage
    - bootstrap/cache

# TODO: Copy nginx web server configs that are laravel specific?
