# Reference: https://laravel.com/docs/5.2
---
# TODO: there must be a better way to do this to make sure composer vars are
# used globally (not per task)? THIS MIGHT NOT BE NEEDED ANY MORE. TEST!
- name: Source the system ENV (make sure ENV VARS load everywhere)
  shell: . /etc/environment

- name: Install laravel installer with composer
  become: yes
  become_user: vagrant
  composer:
    command: "require"
    arguments: "laravel/installer{{ laravel_installer_version }}"
    working_dir: "{{ composer_home }}"

- name: Setup MySQL User
  mysql_user:
    name: vagrant
    password: vagrant
    priv: "{{ project_name }}.*:ALL"
    host: "%"
    state: present

- name: Create project database
  mysql_db: db={{ project_name }} state=present

- name: Ensure that the document root exists.
  file: path="{{ laravel_base }}" state="directory"

- name: Create a Laravel project.
  become: yes
  become_user: vagrant
  shell: laravel new {{ laravel_folder }}
  args:
    chdir: "{{ laravel_base }}"
    creates: "{{ laravel_base }}/{{ laravel_folder }}"

- name: Ensure that the web server can write to directories.
  file:
    path: "{{ laravel_base }}/{{ laravel_folder }}/{{ item }}"
    state: directory
    group: www-data
    mode: g+w
    recurse: yes
  with_items:
    - storage
    - bootstrap/cache

- name: Setting Laravel environment
  template:
    src=env.j2
    dest={{ laravel_base }}/{{ laravel_folder }}/.env
    force=yes

- name: Setting Laravel routes
  template:
    src=routes.php.j2
    dest={{ laravel_base }}/{{ laravel_folder }}/app/Http/routes.php
    owner=vagrant
    group=vagrant
    mode=0644
    force=yes

- name: Setting Laravel controller
  template:
    src=WelcomeController.php.j2
    dest={{ laravel_base }}/{{ laravel_folder }}/app/Http/Controllers/WelcomeController.php
    owner=vagrant
    group=vagrant
    mode=0644

- name: Setting Laravel
  copy:
    src=../files/arrived.blade.php
    dest={{ laravel_base }}/{{ laravel_folder }}/resources/views/arrived.blade.php
    owner=vagrant
    group=vagrant
    mode=0644
