# Reference: https://laravel.com/docs/5.2
---
# TODO: there must be a better way to do this to make sure composer vars are
# used globally (not per task)?
- name: Source the system ENV (make sure ENV VARS load everywhere)
  shell: . /etc/environment

- name: Install laravel installer with composer
  become: yes
  become_user: vagrant
  command: composer global require "laravel/installer{{ laravel_installer_version }}"
  # command: composer global require --prefer-source "laravel/installer{{ laravel_installer_version }}"

- name: Ensure that the document root exists.
  file: path="{{ laravel_base }}" state="directory"

- name: Create a Laravel project.
  become: yes
  become_user: vagrant
  shell: laravel new {{ laravel_folder }}
  args:
    chdir: "{{ laravel_base }}"
    creates: "{{ laravel_base }}/{{ laravel_folder }}"

- name: Ensure that the web server can write to directories.
  file:
    path: "{{ laravel_base }}/{{ laravel_folder }}/{{ item }}"
    state: directory
    group: www-data
    mode: g+w
    recurse: yes
  with_items:
    - storage
    - bootstrap/cache

# Copy Apache web server templates into place that are laravel specific?
# First pass. Perhaps these work here, or perhaps we need to add
# nginx as well or organize these differently?
- name: Configure Laravel Project VirtualHost
  template: src=../templates/apache-vhost.conf.j2 dest=/etc/apache2/sites-available/{{ project_name }}.conf

- name: Configure Laravel Project HTTPS VirtualHost
  template: src=../templates/apache-vhost-ssl.conf.j2 dest=/etc/apache2/sites-available/{{ project_name }}-ssl.conf

- name: Enable Project VirtualHost
  command: a2ensite {{ project_name }}

- name: Enable Project HTTPS VirtualHost
  command: a2ensite {{ project_name }}-ssl

- name: Restart Apache
  service: name=apache2 state=restarted

# TODO: Copy nginx web server configs that are laravel specific?
