---

- name: Install PostgreSQL Packages
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - postgresql-9.3
    - postgresql-contrib-9.3
    - postgresql-client-9.3
    - python-pygresql
    - python-psycopg2

- name: Configure PostgreSQL
  template: src=../templates/postgresql.conf dest=/etc/postgresql/9.3/main/postgresql.conf

- name: Create databases
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ project_name }} state=present


- name: Create users
  sudo: yes
  sudo_user: postgres
  postgresql_user: name=vagrant password=vagrant db={{ project_name }} priv=ALL
