---
- name: Add Percona APT Repository Key
  apt_key: id=1C4CBDCDCD2EFD2A keyserver=keys.gnupg.net validate_certs=no

- name: Add Percona APT Repository
  apt_repository: repo='deb http://repo.percona.com/apt trusty main' state=present update_cache=yes validate_certs=no

- name: Add Percona src APT Repository
  apt_repository: repo='deb-src http://repo.percona.com/apt trusty main' state=present update_cache=yes validate_certs=no

- name: Install Percona MySQL
  apt: name={{ item }} state=present
  with_items:
    - percona-server-server-5.6
    - percona-server-client-5.6
    - python-mysqldb

# - name: Install DB
#   command: mysql_install_db
