---
# http://docs.ansible.com/ansible/composer_module.html
# http://docs.ansible.com/ansible/pear_module.html

# Use PEAR
# - name: Install PHP_CodeSniffer
#   pear: name=PHP_CodeSniffer state=latest

# Use composer
- name: Install Behat
  become: yes
  become_user: vagrant
  composer:
    command: "require"
    arguments: "behat/behat=*"
    working_dir: "{{ devstack_composer_home }}"
  tags:
    - phpqat

- name: Install PHP_Depend
  become: yes
  become_user: vagrant
  composer:
    command: "require"
    arguments: "pdepend/pdepend=*"
    working_dir: "{{ devstack_composer_home }}"
  tags:
    - phpqat

- name: Install PHP_CodeSniffer
  become: yes
  become_user: vagrant
  composer:
    command: "require"
    arguments: "squizlabs/php_codesniffer=*"
    working_dir: "{{ devstack_composer_home }}"
  tags:
    - phpqat

- name: Install PHPUnit
  become: yes
  become_user: vagrant
  composer:
    command: "require"
    arguments: "phpunit/phpunit=*"
    working_dir: "{{ devstack_composer_home }}"
  tags:
    - phpqat

- name: Install vfsStream
  become: yes
  become_user: vagrant
  composer:
    command: "require"
    arguments: "mikey179/vfsStream=*"
    working_dir: "{{ devstack_composer_home }}"
  tags:
    - phpqat

- name: Install PHPMD
  become: yes
  become_user: vagrant
  composer:
    command: "require"
    arguments: "phpmd/phpmd=*"
    working_dir: "{{ devstack_composer_home }}"
  tags:
    - phpqat

- name: Install phploc
  become: yes
  become_user: vagrant
  composer:
    command: "require"
    arguments: "phploc/phploc=*"
    working_dir: "{{ devstack_composer_home }}"
  tags:
    - phpqat

- name: Install phpdox
  become: yes
  become_user: vagrant
  composer:
    command: "require"
    arguments: "theseer/phpdox=*"
    working_dir: "{{ devstack_composer_home }}"
  tags:
    - phpqat

- name: Install phpmetrics
  become: yes
  become_user: vagrant
  composer:
    command: "require"
    arguments: "halleck45/phpmetrics=*"
    working_dir: "{{ devstack_composer_home }}"
  tags:
    - phpqat

- name: Install phpcpd
  become: yes
  become_user: vagrant
  composer:
    command: "require"
    arguments: "sebastian/phpcpd=*"
    working_dir: "{{ devstack_composer_home }}"
  tags:
    - phpqat

- name: Install qa-tools
  become: yes
  become_user: vagrant
  composer:
    command: "require"
    arguments: "qa-tools/qa-tools=*"
    working_dir: "{{ devstack_composer_home }}"
  tags:
    - phpqat
