---
allow_duplicates: no
dependencies:
  - role: drush
    drush_hostname: "{{ drupal_hostname }}"
    drush_docroot: "{{ drupal_docroot }}"
#   - { role: composer }
#   - { role: php }
#   - { role: apache }
  - role: apache-config
    apache_name: "drupal"
    apache_hostname: "{{ drupal_hostname }}"
    apache_docroot: "{{ drupal_docroot }}"
#   - { role: mysql }
#   - { role: nodejs }
#   - { role: git }
#   - { role: common }
