---
allow_duplicates: no
dependencies:
  - { role: drush }
#   - { role: composer }
#   - { role: php }
#   - { role: apache }
  - { role: apache-config, apache_docroot: "{{ drupal_docroot }}" }
#   - { role: mysql }
  - role: database-config
    database_name: "{{ drupal_db_name }}"
    database_user: "{{ drupal_db_user }}"
    database_password: "{{ drupal_db_password }}"
    database_dump: "{{ drupal_db_dump }}"
#   - { role: nodejs }
#   - { role: git }
#   - { role: common }
