---
allow_duplicates: no
dependencies:
  - { role: drush }
#   - { role: composer }
#   - { role: php }
#   - { role: apache }
  - { role: apache-config, apache_docroot: "{{ drupal_docroot }}" }
#   - { role: mysql }
#   - { role: nodejs }
#   - { role: git }
#   - { role: common }
