---
- name: NodeJS - Get APT repository setup script
  get_url: url=https://deb.nodesource.com/setup_5.x dest=/tmp/nodejs_setup mode=0755

- name: NodeJS - Run repository setup script
  sudo: yes
  command: sudo bash nodejs_setup chdir=/tmp

- name: Install NodeJS
  sudo: yes
  apt: name={{ item }} state=present
  with_items:
    - nodejs
