---
- name: Download Drupal 8 RC1
  get_url: url=http://ftp.drupal.org/files/projects/drupal-8.0.0-rc1.tar.gz dest=/tmp
  tags:
    - drupal

- name: Decompress D8 RC1 tarball
  shell: tar zxvf /tmp/drupal-8.0.0-rc1.tar.gz -C /tmp
  tags:
    - drupal

- name: Move D8 RC1 to project docroot
  shell: "mv /tmp/drupal-8.0.0-rc1/* {{ project_docroot }}; mv /tmp/drupal-8.0.0-rc1/.* {{ project_docroot }}"
  ignore_errors: yes
  tags:
    - drupal

- name: Clean up - Delete D8 tarball
  shell: "rm -f /tmp/drupal-8.0.0-rc1.tar.gz; rm -rf /tmp/drupal-8.0.0-rc1"
  tags:
    - drupal

# Install Coding Standards tools here or perhaps on the host via bootstrap?
