---
- name: Install Drush
  get_url: url=https://github.com/drush-ops/drush/releases/download/8.0.3/drush.phar dest=/usr/local/bin/drush mode=0755

- name: Ensure /etc/drush directory exists
  file:
    path: /etc/drush
    state: directory

- name: Configure project default local Drush aliases
  template:
    src: project.aliases.drushrc.php.j2
    dest: /etc/drush/{{ project_name }}.aliases.drushrc.php

- name: Enable drush autocomplete and more
  # This will only affect the user vagrant.
  command: drush -y init creates=~/.drush/drush.complete.sh
  become: no
