---
- name: Install Composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=0755

# NOTE: We setup the paths to keep composer in a truly globally shared location
# (and not in a user . directory during install time)
# NOTE: This is an attempt to keep libraries in a shared location. If this does not
# work for your project, adjust as needed. It also allows for a consistent bin location.
#
# Most of the time this VM is used to host a single site so this works. If your
# project contains multiple sites, you might need to adjust this.
- name: Create a COMPOSER_HOME directory
  file: path={{ composer_home }} state=directory

# - name: Create a COMPOSER_VENDOR_DIR directory
#   file: path={{ composer_home }}/vendor state=directory

- name: Set COMPOSER_HOME environment variable
  lineinfile:
    line: 'COMPOSER_HOME="{{ composer_home }}"'
    dest: /etc/environment
    state: present
    insertafter: EOF
  environment:
    COMPOSER_HOME: "{{ composer_home }}"

# Leave this disable to allow non-global installs to run in ./vendor (stuff
# you want to commit) while still allowing global installs to run in COMPOSER_HOME/vendor
# - name: Set COMPOSER_VENDOR_DIR environment variable
#   lineinfile:
#     line: 'COMPOSER_VENDOR_DIR="{{ composer_home }}/vendor"'
#     dest: /etc/environment
#     state: present
#     insertafter: EOF
#   environment:
#     COMPOSER_VENDOR_DIR: "{{ composer_home }}/vendor"

# Keep the binaries in a consistent location so we can make sure they are in PATH
- name: Set COMPOSER_BIN_DIR environment variable
  lineinfile:
    line: 'COMPOSER_BIN_DIR="{{ composer_home }}/vendor/bin"'
    dest: /etc/environment
    state: present
    insertafter: EOF
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ composer_home }}/vendor/bin"
    COMPOSER_BIN_DIR: "{{ composer_home }}/vendor/bin"

- name: Setting permissions on COMPOSER_HOME
  command: chmod -R 775 {{ composer_home }}

- name: Setting group permissions on COMPOSER_HOME
  command: chgrp -R vagrant {{ composer_home }}

- name: Set PATH to include Composer Global bin
  lineinfile:
    dest: /etc/environment
    state: present
    backrefs: yes
    regexp: 'PATH=(["]*)((?!.*?{{ composer_home }}\/vendor\/bin).*?)(["]*)$'
    line: 'PATH={{ composer_home }}/vendor/bin:\1\2\3'

# - name: Source the system ENV (make sure ENV VARS load everywhere)
#   shell: . /etc/environment
#
# # TODO: we likely need to change this or ask users to enter this, sadly.
# # TODO: this token is an example personal token to be replaced with your own.
# # https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+devstack+2016-02-20+0147
# # When install package via composer you will hit API limits and will need to add
# # your own like so:

# - name: Set Composer GitHub Personal OAuth Token Example (update with your own)
#   become: yes
#   become_user: vagrant
#   command: composer config --global github-oauth.github.com 6ebd8aa451c65b6880adc9c2c6bc6fd60a9147c8
#   # creates /usr/local/share/composer/auth.json
