---
- hosts: local
  become: no
  roles:
    ## package managers and some basic tools required elsewhere
    - { role: common, tags: ['common'] }
    ## VirtualBox
    # - { role: virtualbox, tags: ['virtualbox'] }
    ## Vagrant and related
    - { role: vagrant, tags: ['vagrant'] }
    ## PHP and composer
    - { role: php, tags: ['php'] }
    ## PHP QA Toolchain
    - { role: php_qat, tags: ['php_qat'] }
    ## WordPress CLI tools
    # - { role: wp_cli, tags: ['wp_cli'] }
