# The boostrap script installs Homebrew and Ansible before running this
# playbook. The Homebrew install script makes sure that the Mac command-line
# tools are installed.
# TODO: run brew doctor if already installed? make sure things are right?
---
- hosts: local
  become: no
  roles:
    ## package managers and some basic tools required elsewhere
    - { role: common, tags: ['common'] }
    ## Parallels Desktop
    - { role: parallels, tags: ['parallels'] }
    ## VirtualBox
    # - { role: virtualbox, tags: ['virtualbox'] }
    ## TODO: install Parallels
    ## Vagrant and related
    - { role: vagrant, tags: ['vagrant'] }
    ## PHP and composer
    - { role: php, tags: ['php'] }
    ## PHP QA Toolchain
    - { role: php_qat, tags: ['php_qat'] }
    ## WordPress CLI tools
    # - { role: wp_cli, tags: ['wp_cli'] }
    ## TODO: install coder for drupal coding standards linting
    ## Front end tools
    - { role: fe_tools, tags: ['fe_tools'] }
    ## Java
    # - { role: java, tags: ['java'] }
    ## Hosting Services tools
    # - { role: hosting_services, tags: ['hosting_services'] }

    ## Install tools for running automated QA on host machines.
    ## Especially useful for browser testing automation tools such as WebDriver
    ## based tests.
    ## TODO: install WebDriver

    ## Trigger other dependency installs?
    ## `composer install`
    ## `npm install`
    ## `bower install`
