---
- hosts: local
  become: no
  roles:
    ## package managers and some basic tools required elsewhere
    - { role: common, tags: ['common'] }
    ## Vagrant and related
    - { role: vagrant, tags: ['vagrant'] }
