---
galaxy_info:
  author: Rahmin Pavlovic
  description: 
  company: EY
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - web