---
allow_duplicates: no
dependencies:
#   - { role: common }
#   - { role: git }
  - { role: composer }
#   - { role: php }
#   - { role: apache }
  - role: apache-config
    apache_name: "laravel"
    apache_hostname: "{{ laravel_hostname }}"
    apache_docroot: "{{ laravel_docroot }}"
