---
allow_duplicates: no
dependencies:
#   - { role: common }
#   - { role: git }
  - { role: composer }
#   - { role: php }
#   - { role: apache }
  - { role: apache-config, apache_docroot: "{{ laravel_docroot }}" }
  - role: database-config
    database_name: "{{ laravel_db_name }}"
    database_user: "{{ laravel_db_user }}"
    database_password: "{{ laravel_db_password }}"
    database_dump: "{{ laravel_db_dump }}"
