---
- name: Install MongoDB
  apt: name={{ item }} state=present
  with_items:
    - mongodb
    - python-pymongo

- name: Configure MongoDB
  template: src=../templates/mongodb.conf.j2 dest=/etc/mongodb.conf

- name: Restart MongoDB
  service: name=mongodb state=restarted

- name: Create MongoDB project database and user
  mongodb_user: database={{ project_name }} name=vagrant password=vagrant state=present
