---
- name: Ensure that the document root exists.
  file: path="{{ devstack_docroot }}" state="directory"

- name: Test if an index.php is present
  stat: path="{{ devstack_docroot }}/index.php"
  register: index_present

- name: Copy files to the document root.
  copy: src="{{ item }}" dest="{{ devstack_docroot }}"
  with_items:
    - index.php
    - index.html
  when: not index_present.stat.exists

- name: Setup MySQL User
  mysql_user:
    name: vagrant
    password: vagrant
    priv: "{{ project_name }}.*:ALL"
    host: "%"
    state: present

- name: Create project database
  mysql_db: db={{ project_name }} state=present
