---
- name: Copy SSH key
  copy:
    src: "{{ user_private_key }}"
    dest: /home/vagrant/.ssh/id_rsa
    mode: 0600
    force: yes

- name: Validate SSH authorized_keys permissions
  command: chmod 600 /home/vagrant/.ssh/authorized_keys

- name: Validate SSH directory permissions
  command: chmod 700 /home/vagrant/.ssh
