---
# To install a base LAMP stack enable "mysql, apache, php"
# From there, enable any other tools your project requires.

# TODO: To install a base MEAN stack enable "mongodb, express, angular, nodejs"
# From there, enable any other tools your project requires.

# To install a starter site and the dependant stack, simply enable your
# desired tool such as "drupal", "wordpress", "laravel", "symfony", etc...

# apt-get update and some basic tools required elsewhere
- include: roles/common.yml

# Include your private SSH key in the VM
- include: roles/ssh.yml

# Git and your private .gitconfig in the VM
- include: roles/git.yml

# Vim and some standard plugins in the VM
- include: roles/vim.yml

# Additional Tools
- include: roles/nodejs.yml # Includes npm

# Database
- include: roles/mysql.yml
# - include: roles/mariadb.yml
# - include: roles/percona.yml
# - include: roles/mongodb.yml
# - include: roles/pgsql.yml

# Web Server
- include: roles/apache.yml
# - include: roles/nginx.yml # TODO

# Project Language (PHP)
- include: roles/php.yml
# - include: roles/php-fpm.yml # TODO
# - include: roles/composer.yml

# Project Language (Ruby)
# - include: roles/bundler.yml

# Cacheing Layers
# - include: roles/memcached.yml
# - include: roles/redis.yml
# - include: roles/varnish.yml

# Background Job Queue
# - include: roles/resque.yaml # TODO

# Search Engine
# - include: roles/solr.yml # TODO

# Drupal and Tools
# - include: roles/drush.yml
# - include: roles/acquia_insight.yml
# - include: roles/drupal7.yml # Disable after first run to not overwrite everytime
# - include: roles/drupal_console.yml
# - include: roles/drupal8.yml # Disable after first run to not overwrite everytime

# Wordpress and Tools
# - include: roles/wordpress.yml # TODO

# Laravel and Tools
# - include: roles/laravel.yml # TODO

# Symfony and Tools
# - include: roles/symfony.yml

# Front End UI Theming Tools
# - include: roles/sass.yml
# - include: roles/gulp.yml
# - include: roles/grunt.yml
# - include: roles/bower.yml
# - include: roles/yeoman.yml
# - include: roles/browsersync.yml

# QA Tools
# - include: roles/wraith.yml # TODO
# - include: phpcqt.yml # TODO Various PHP Code Quality tools in VM
# - include: roles/jasmine.yml # TODO

# Project Documentation Tools
# - include: roles/mkdocs.yml
# - include: roles/phpdocumentor.yml # TODO
# - include: roles/jekyll.yml

# TODO: Local admin tools to provide admin and analytics in vm
# TODO: Put these in an admin dir that is gitignored?
# - include: roles/phpmyadmin.yml # TODO
# - include: roles/memcachedadmin.yml # TODO
# - include: roles/redis-commander.yml
# - include: roles/redis-stat.yml # TODO
# - include: roles/webgrind.yml # TODO
# - include: roles/phing.yml # TODO

# Project Site Configuration (any special configs)
- include: roles/project.yml
