---
# To install a base LAMP stack enable "mysql, apache, php"
# From there, enable any other tools your project requires.

# To install a base MEAN stack enable "mongodb, express, angular, nodejs"
# From there, enable any other tools your project requires.

# apt-get update and some basics
- include: common.yml

# Include your private SSH key in the VM
- include: ssh.yml

# Git and your private .gitconfig in the VM
- include: git.yml

# Database
- include: mysql.yml
# - include: mariadb.yml
# - include: percona.yml
# - include: mongodb.yml

# Web Server
- include: apache.yml
# - include: nginx.yml

# Project Language (PHP)
- include: php.yml
# - include: php-fpm.yml
# - include: composer.yml

# Cacheing Layers
# - include: memcached.yml
# - include: redis.yml
# - include: varnish.yml

# Drupal Tools
# - include: drush.yml
# - include: acquia_insight.yml

# Wordpress Tools

# Theming/UI Tools
# - include: nodejs.yml

# Project Site Configuration (any special configs)
- include: project.yml
