---
# To install a base LAMP stack enable "database, apache, php"
# From there, enable any other tools your project requires.

# TODO: To install a base MEAN stack enable "mongodb, express, angular, nodejs"
# From there, enable any other tools your project requires.

# To install a starter site and the dependant stack, simply enable your
# desired tool such as "drupal", "wordpress", "laravel", "symfony", etc...

- hosts: devstack
  sudo: yes
  roles:
    ## apt-get update and some basic tools required elsewhere
    - { role: common, tags: ['common'] }

    ## Include your private SSH key in the VM
    - { role: ssh, tags: ['ssh'] }

    ## Git and your private .gitconfig in the VM
    - { role: git, tags: ['git'] }

    ## Vim and some standard plugins in the VM
    - { role: vim, tags: ['vim'] }

    ## Additional Tools
    - { role: nodejs, tags: ['nodejs'] } # Includes npm

    ## Database
    - { role: database, tags: ['mysql'] }
    # - { role: database, tags: ['mariadb'], database_provider: 'mariadb' }
    # - { role: database, tags: ['percona'], database_provider: 'percona' }
    # - { role: mongodb, tags: ['mongodb'] }
    # - { role: postgresql, tags: ['postgresql'] }
    # - { role: sqlite, tags: ['sqlite'] }

    ## Web Server
    - { role: apache, tags: ['apache'] }
    # - { role: nginx, tags: ['nginx'] } # TODO

    ## Project Language (PHP)
    - { role: php, tags: ['php'] }
    # - { role: php-fpm, tags: ['php-fpm'] } # TODO
    - { role: composer, tags: ['composer'] }
    # - { role: phpqat, tags: ['phpqat'] }

    ## Project Language (Ruby)
    # - { role: bundler, tags: ['bundler'] }

    ## Project Language (Java)
    ## If you want to install Oracle's JRE/JDK, then make sure to read the instructions.
    # - { role: java-oracle, tags: ['java-oracle'] }
    # - { role: java-open, tags: ['java-open'] }

    ## Cacheing Layers
    # - { role: memcached, tags: ['memcached'] }
    # - { role: redis, tags: ['redis'] }
    # - { role: varnish, tags: ['varnish'] }

    ## Background Job Queue
    # - { role: resque, tags: ['resque'] } # TODO
    # - { role: beanstalkd, tags: ['beanstalkd'] }

    ## Search Engine
    # - { role: solr, tags: ['solr'] } # TODO

    ## Default LAMP Stack: make sure that it all works OOTB.
    - { role: devstack, tags: ['devstack'] }

    ## Drupal and Tools
    # - { role: drush, tags: ['drush'] }
    # - { role: drupal_console, tags: ['drupal_console'] }
    # - { role: drupal, tags: ['drupal'] }
    # - { role: acquia_insight, tags: ['acquia_insight'] }
    # - { role: acquia_cloud_hooks, tags: ['acquia_cloud_hooks'] } # TODO
    # - { role: pantheon_termius, tags: ['pantheon_termius'] } # TODO

    # Wordpress and Tools
    # - { role: wordpress, tags: ['wordpress'] }

    # Laravel and Tools
    # - { role: laravel, tags: ['laravel'] }

    # Symfony and Tools
    # - { role: symfony, tags: ['symfony'] }

    # Front End UI Theming Tools
    # - { role: sass, tags: ['sass'] }
    # - { role: gulp, tags: ['gulp'] }
    # - { role: grunt, tags: ['grunt'] }
    # - { role: bower, tags: ['bower'] }
    # - { role: yeoman, tags: ['yeoman'] }
    # - { role: browsersync, tags: ['browsersync'] }

    # QA Tools
    # - { role: wraith, tags: ['wraith'] } # TODO
    # - { role: jasmine, tags: ['jasmine'] } # TODO

    # Continuous integration
    # - { role: teamcity, tags: ['teamcity'] }

    # Performance/Debugging Tools/Services
    # - { role: blackfire, tags: ['blackfire'] }

    # Project Documentation Tools
    # - { role: mkdocs, tags: ['mkdocs'] }
    # - { role: phpdocumentor, tags: ['phpdocumentor'] } # TODO
    # - { role: jekyll, tags: ['jekyll'] }

    # TODO: Local admin tools to provide admin and analytics in vm
    # TODO: Put these in an admin dir that is gitignored?
    # - { role: phpmyadmin, tags: ['phpmyadmin'] } # TODO
    # - { role: memcachedadmin, tags: ['memcachedadmin'] } # TODO
    # - { role: redis-commander, tags: ['redis-commander'] }
    # - { role: redis-stat, tags: ['redis-stat'] } # TODO
    # - { role: webgrind, tags: ['webgrind'] } # TODO
    # - { role: phing, tags: ['phing'] } # TODO

    # Managed hosting solution tools
    # - { role: azure-cli, tags: ['azure-cli'] }
    # - { role: aws-cli, tags: ['aws-cli'] } # TODO

    # Project Site Configuration (any special configs)
    - { role: project, tags: ['project'] }
