---
# To install a base LAMP stack enable "mysql, apache, php"
# From there, enable any other tools your project requires.

# TODO: To install a base MEAN stack enable "mongodb, express, angular, nodejs"
# From there, enable any other tools your project requires.

# To install a starter site and the dependant stack, simply enable your
# desired tool such as "drupal", "wordpress", "laravel", "symfony", etc...

- hosts: devstack
  sudo: yes
  roles:
    ## apt-get update and some basic tools required elsewhere
    - common

    ## Include your private SSH key in the VM
    - ssh

    ## Git and your private .gitconfig in the VM
    - git

    ## Vim and some standard plugins in the VM
    - vim

    ## Additional Tools
    - nodejs # Includes npm

    ## Database
    - mysql
    # - mariadb
    # - percona
    # - mongodb
    # - postgresql
    # - sqlite

    ## Web Server
    - apache
    # - nginx # TODO

    ## Project Language (PHP)
    - php
    # - php-fpm # TODO
    - composer
    # - phpqat

    ## Project Language (Ruby)
    # - bundler

    ## Cacheing Layers
    # - memcached
    # - redis
    # - varnish

    ## Background Job Queue
    # - resque # TODO
    # - beanstalkd

    ## Search Engine
    # - solr # TODO

    ## Default LAMP Stack: make sure that it all works OOTB.
    - devstack

    ## Drupal and Tools
    # - drush
    # - acquia_insight
    # - drupal7 # Disable after first run to not overwrite everytime
    # - drupal_console
    # - drupal8 # Disable after first run to not overwrite everytime

    # Wordpress and Tools
    # - wp-cli
    # - wordpress

    # Laravel and Tools
    # - laravel

    # Symfony and Tools
    # - symfony

    # Front End UI Theming Tools
    # - sass
    # - gulp
    # - grunt
    # - bower
    # - yeoman
    # - browsersync

    # QA Tools
    # - wraith # TODO
    # - jasmine # TODO

    # Performance/Debugging Tools/Services
    # - blackfire

    # Project Documentation Tools
    # - mkdocs
    # - phpdocumentor # TODO
    # - jekyll

    # TODO: Local admin tools to provide admin and analytics in vm
    # TODO: Put these in an admin dir that is gitignored?
    # - phpmyadmin # TODO
    # - memcachedadmin # TODO
    # - redis-commander
    # - redis-stat # TODO
    # - webgrind # TODO
    # - phing # TODO

    # Managed hosting solution tools
    # - azure-cli

    # Project Site Configuration (any special configs)
    - project
