---
- name:  Install host front-end tools for running processes locally
  homebrew: name={{ item }} state=present update_homebrew=no
  with_items: fe_tools_brew

- name:  Install host front-end node modules
  npm: name={{ item }} global=yes state=present
  with_items: fe_tools_npm

