---
- name: Install Beanstalkd
  apt: name={{ item }} state=present
  with_items:
    - beanstalkd
  tags:
    - beanstalkd

- name: Restart beanstalkd
  service: name=beanstalkd state=restarted enabled=yes
  tags:
    - beanstalkd
