---
- name: Installing WP-CLI
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/bin/wp
    mode: 0755

- name: Test whether Wordpress is present.
  stat: path="{{ wordpress_docroot }}/wp-config.php"
  register: wordpress_present

- name: Downloading Wordpress
  shell: wp core download --path={{ wordpress_docroot }}
  when: not wordpress_present.stat.exists
  become: no

- name: Configuring Wordpress
  shell: >
    wp core config
    --dbname={{ wordpress_db_name }}
    --dbuser={{ wordpress_db_user }}
    --dbpass={{ wordpress_db_password }}
    --path={{ wordpress_docroot }}
  when: not wordpress_present.stat.exists
  become: no

- name: Test whether Wordpress is installed
  command: wp core is-installed --path={{ wordpress_docroot }}
  register: wordpress_installed
  changed_when: false
  ignore_errors: yes
  become: no

- name: Installing Wordpress
  shell: >
    wp core install
    --url="http://{{ wordpress_hostname }}"
    --title="{{ wordpress_sitename }}"
    --admin_user="{{ wordpress_admin_user }}"
    --admin_password="{{ wordpress_admin_pass }}"
    --admin_email="{{ wordpress_admin_email }}"
    --path={{ wordpress_docroot }}
  when: wordpress_installed | failed
  become: no

# - name: Additional Wordpress provisioning
  # shell: >
    # wp rewrite structure "/%postname%/" --path={{ wordpress_docroot }}
  # become: no
  # shell: >
    # wp plugin install http://downloads.wordpress.org/plugin/relative-url.zip
    # --activate
    # --path={{ wordpress_docroot }}
  # become: no
  # shell: >
    # wp plugin install http://downloads.wordpress.org/plugin/w3-total-cache.zip
    # --activate
    # --path={{ wordpress_docroot }}
  # become: no
  # shell: wp theme install twentyfifteen --activate
  # become: no
