---
- name: Install MariaDB Server and Client
  apt: name={{ item }} state=present
  with_items:
    - mariadb-server
    - mariadb-client
    - python-mysqldb

# - name: Install DB
#   command: mysql_install_db

- name: Configure MariaDB
  template: src=../templates/my.cnf.j2 dest=/etc/mysql/my.cnf

- name: Restart MariaDB
  service: name=mysql state=restarted
