---
laravel_installer_version: '=*'
# Optionally set a semantic version http://semver.org
#laravel_installer_version: '=~1.3'
laravel_base: '{{ project_docroot }}'
laravel_folder: 'laravel'

# Apache parameters
laravel_docroot: '{{ laravel_base }}/{{ laravel_folder }}/public'
laravel_hostname: '{{ project_hostname }}'
laravel_port: "80"
laravel_ssl_port: "443"

# Database parameters
laravel_db_name: laravel
laravel_db_user: vagrant
laravel_db_password: vagrant
laravel_db_dump: false
